### ISSUE TITLE
Result View

### ISSUE THREAD

**Issue by abetoluwani** [mensapc/vrep-elementary-back#122]
- [x] Pupils Name
- [x] Class
- [x] Term 
- [x] Session and Term (Current Year and  Term selected by the teacher when trying to input result)

![Image](https://github.com/Mensa-Philosophical-Circle/RPMS-Back/assets/101352514/b38e0ead-946c-4be3-b442-32c8b582af68)

- [x] #127

![Image](https://github.com/Mensa-Philosophical-Circle/RPMS-Back/assets/101352514/f2508e47-b5f1-47d4-bb19-ed1f683107c4)

which is this

![Image](https://github.com/Mensa-Philosophical-Circle/RPMS-Back/assets/101352514/7c632f2d-86c1-472f-a731-a28a16a1b431)

- [x] Pupil Average Score  = (Overall Total Score / (Number of subject registered by the pupils teacher  *100) * 100)

So for example a pupil overall total score is 979 has stated about and the number of the subject registered by the teacher is 12 to get the pupils average score 
                979/(12* 100) = 979/1200 = 0.815833
                  0.815833 * 100 = 81.58 (Pupil Average Score)

- [ ] Highest Average in Class 
This is a bit tricky but here is the catch previously we calculated one pupils average score but for this one here we are looking for the highest pupil average score in a class after calculating the pupils average score 

Let's say in a class of 4 after calculating each pupils average score which have  85.11, 81.58,  56.98, 96.56 
              As we can see the highest average score here is 96.56

- [x] #128
- [x] No of day School Opened ; No of Days Present ; No of Days Absent = Based on the teachers input on attendance
- [x] Subject - List of Subject registered by the pupils teacher
- [x] Welcome Test ; Mid Term Test ; Project ; Online Exam; Exam ; Overall reach out to @muhenge  for this

- [x] Grade  this issue is to be addressed  in #101 

- [x] #129
 Maths 
- Pupil 1 = 76/100
- Pupil 2 = 89/100
- Pupil 3 = 50/100
The highest score in the class is pupil 2 score  while the lowest score  in class is  pupil 3 score

- [x] Remark Should be handled already in #101 

- [ ] Affective trait , psychomotor skills, Teachers remark , head teacher remark  , Next Term Begins = refer are all input required in Pupil Profile (Teacher Remark) #120 
- [ ]
